version: "3"
services:
  streamlit:
    build: .
    container_name: streamlit_app
    expose:
      - "8501"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8051:80" # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./error.html:/usr/share/nginx/html/custom_403.html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
